version: "3.3"
volumes:
  db:
    driver:
      local
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: todo
    container_name: todo
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todo-network

  #  db:
  #    image: mysql:8
  #    restart: unless-stopped
  #    environment:
  #      MYSQL_DATABASE: ${DB_DATABASE}
  #      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #      MYSQL_PASSWORD: ${DB_PASSWORD}
  #      MYSQL_USER: ${DB_USERNAME}
  #    networks:
  #      - instragram-network
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_PASSWORD: todo
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - todo-network

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - 443:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - todo-network

networks:
  instragram-network:
    driver: bridge
